/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.abd.coronavirus.view;

//import co.edu.usbbog.ing.sis.persona.controller.logic.Unificador;
import co.edu.usbbog.abd.coronavirus.controller.logic.Unificador;
import co.edu.usbbog.abd.coronavirus.model.Coronavirus;
import co.edu.usbbog.abd.coronavirus.model.TxtJava;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JPanel;

/**
 *
 * @author 304
 */
public class Principal extends javax.swing.JFrame {

    private Inicio inicioJPanel;
    private VehiculoView pv;
    private TxtJava txt;

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.txt = new TxtJava();

        this.setTitle("Grafica");
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        iniciar();
        //initComponents();

        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    protected void registrarCoronavirus(Coronavirus o) {
        txt.insertarDato(o.getNombreP(), o.getNumcont(), o.getNumdead());
        txt.ActualizarArrayList();
        txt.guardarFichero();
    }

    protected void mostrarCoronavirus() {
        txt.MostrarObjetos();
    }

//    protected void ordenarCoronavirus() {
//        p1.ordenaBurbuja();
//    }

    protected void eliminarCoronavirus(String nombrePais) {
        txt.eliminarFicheroPorNombrePais(nombrePais);
        txt.guardarFichero();
        txt.ActualizarArrayList();
    }

    protected void modificarCoronavirus(Coronavirus o) {
        txt.modificarFichero(o.getNombreP(), o.getNumcont(), o.getNumdead());
        txt.guardarFichero();
        txt.ActualizarArrayList();
    }

    protected void irAVehiculoView(JPanel jPanel) {
        remove(jPanel);
        pv = new VehiculoView(this);
        pv.setVisible(true);
        add(pv);
        pack();
        setLocationRelativeTo(null);
    }

    public void iniciar() {
        inicioJPanel = new Inicio(this);
        inicioJPanel.setVisible(true);
        add(inicioJPanel);
        pack();
        setLocationRelativeTo(null);
    }
    
    public void comprobarFichero(){
        txt.comprobarBd();
    }
    
    public void OrdenarPorNumContagiados(){
        txt.ordenarFicheroPorNumeroContagios();
    }
    
    public void OrdenarPorNumMuertos(){
        txt.ordenarFicheroPorNumeroMuertes();
    }
}

/**
 * this.pl = new Unificador(); this.setTitle("Grafica"); this.setVisible(true);
 * this.setDefaultCloseOperation(EXIT_ON_CLOSE); this.pv = new
 * PersonaView(this); this.pv.setVisible(true); this.add(pv); this.pack();
 * this.setLocationRelativeTo(null);
 */
