/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.abd.coronavirus.view;

//import co.edu.usbbog.ing.sis.persona.controller.prototype.Dueno;
//import co.edu.usbbog.ing.sis.persona.controller.prototype.G_entrada;
import co.edu.usbbog.abd.coronavirus.model.Coronavirus;
import javax.swing.JOptionPane;

/**
 *
 * @author 304
 */
public class VehiculoView extends javax.swing.JPanel {

    private Principal D;

    /**
     * Creates new form Vehiculo
     */
    public VehiculoView(Principal principal) {
        this.D = principal;
        D.comprobarFichero();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        campo_nombre_pais = new javax.swing.JTextField();
        campo_numero_contagios = new javax.swing.JTextField();
        campo_numero_muertos = new javax.swing.JTextField();
        campo_eliminar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButtonBuscar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        ordenarPorContagios = new javax.swing.JButton();
        ordenarPorMuertes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelName.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelName.setText("Numero contagios");

        jLabelID.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelID.setText("Nompre Pais");

        jLabelUser.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelUser.setText("Numero muertes");

        jLabelPass.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelPass.setText("Eliminar por pais");

        campo_nombre_pais.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_numero_contagios.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_numero_muertos.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_eliminar.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        jButtonBuscar.setBackground(new java.awt.Color(153, 0, 0));
        jButtonBuscar.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Actualizar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 0, 0));
        jButton6.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Regitrar casos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel5.setText("Contactanos: ");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel6.setText("Telefono: 3504734161");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel7.setText("Email: pcmasterscomponentes@gmail.com");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ing/sis/persona/logo/logo_instagram.png"))); // NOI18N
        jLabel8.setText("@pcmasterscomponentes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jButton8.setBackground(new java.awt.Color(153, 0, 0));
        jButton8.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonBuscar1.setBackground(new java.awt.Color(153, 0, 0));
        jButtonBuscar1.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButtonBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar1.setText("Eliminar");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ing/sis/persona/logo/Coronaviruslogo.jpg"))); // NOI18N

        jButton9.setBackground(new java.awt.Color(153, 0, 0));
        jButton9.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Cargar Casos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        ordenarPorContagios.setBackground(new java.awt.Color(153, 0, 0));
        ordenarPorContagios.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        ordenarPorContagios.setForeground(new java.awt.Color(255, 255, 255));
        ordenarPorContagios.setText("Organizar por Número de contagiados");
        ordenarPorContagios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPorContagiosActionPerformed(evt);
            }
        });

        ordenarPorMuertes.setBackground(new java.awt.Color(153, 0, 0));
        ordenarPorMuertes.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        ordenarPorMuertes.setForeground(new java.awt.Color(255, 255, 255));
        ordenarPorMuertes.setText("Organizar por Número de muertes");
        ordenarPorMuertes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPorMuertesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_numero_contagios, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nombre_pais)
                            .addComponent(campo_numero_muertos)
                            .addComponent(campo_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ordenarPorContagios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ordenarPorMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonBuscar)
                                .addGap(59, 59, 59)
                                .addComponent(jButtonBuscar1)
                                .addGap(42, 42, 42)
                                .addComponent(jButton8)
                                .addGap(28, 28, 28)
                                .addComponent(jButton9)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nombre_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_numero_contagios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_numero_muertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPass))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonBuscar1)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarPorContagios)
                    .addComponent(ordenarPorMuertes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        actualizar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        registrarCoronavirus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        modificar();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar1ActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        cargarCasosAmerica();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ordenarPorContagiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPorContagiosActionPerformed
        D.OrdenarPorNumContagiados();
    }//GEN-LAST:event_ordenarPorContagiosActionPerformed

    private void ordenarPorMuertesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPorMuertesActionPerformed
        D.OrdenarPorNumMuertos();
    }//GEN-LAST:event_ordenarPorMuertesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_eliminar;
    private javax.swing.JTextField campo_nombre_pais;
    private javax.swing.JTextField campo_numero_contagios;
    private javax.swing.JTextField campo_numero_muertos;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ordenarPorContagios;
    private javax.swing.JButton ordenarPorMuertes;
    // End of variables declaration//GEN-END:variables

    private void registrarCoronavirus() {

        if (validar()) {
            Coronavirus coro = new Coronavirus(
                    campo_nombre_pais.getText(),
                    Integer.parseInt(campo_numero_contagios.getText()),
                    Integer.parseInt(campo_numero_muertos.getText()));

            D.registrarCoronavirus(coro);
        } else {
            JOptionPane.showMessageDialog(this, "Faltan datos por ingresar");
        }

    }

//    public void organizar(){
//        D.ordenarCoronavirus();
//    }
    private void cargarCasosAmerica() {

        D.registrarCoronavirus(new Coronavirus("Chile", 1306, 4));
        D.registrarCoronavirus(new Coronavirus("Argentina", 502, 9));
        D.registrarCoronavirus(new Coronavirus("Paraguay", 41, 3));
        D.registrarCoronavirus(new Coronavirus("Bolivia", 43, 0));
        D.registrarCoronavirus(new Coronavirus("Peru", 580, 9));
        D.registrarCoronavirus(new Coronavirus("Ecuador", 1403, 34));
        D.registrarCoronavirus(new Coronavirus("Brasil", 2915, 77));
        D.registrarCoronavirus(new Coronavirus("Venezuela", 106, 0));
        D.registrarCoronavirus(new Coronavirus("Antigua y Barbuda", 7, 0));
        D.registrarCoronavirus(new Coronavirus("Bahamas", 9, 0));
        D.registrarCoronavirus(new Coronavirus("Belice", 2, 0));
        D.registrarCoronavirus(new Coronavirus("Canada", 3909, 38));
        D.registrarCoronavirus(new Coronavirus("Colombia", 491, 6));
        D.registrarCoronavirus(new Coronavirus("Costa Rica", 231, 2));
        D.registrarCoronavirus(new Coronavirus("Cuba", 67, 1));
        D.registrarCoronavirus(new Coronavirus("Republica Dominicana", 488, 10));
        D.registrarCoronavirus(new Coronavirus("El Salvador", 13, 0));
        D.registrarCoronavirus(new Coronavirus("Estados Unidos", 83507, 1201));
        D.registrarCoronavirus(new Coronavirus("Granada", 7, 0));
        D.registrarCoronavirus(new Coronavirus("Guatemala", 24, 1));
        D.registrarCoronavirus(new Coronavirus("Guyana", 5, 1));
        D.registrarCoronavirus(new Coronavirus("Haiti", 8, 0));
        D.registrarCoronavirus(new Coronavirus("Honduras", 52, 1));
        D.registrarCoronavirus(new Coronavirus("Hamaica", 26, 1));
        D.registrarCoronavirus(new Coronavirus("Mexico", 475, 6));
        D.registrarCoronavirus(new Coronavirus("Nicaragua", 2, 0));
        D.registrarCoronavirus(new Coronavirus("Panama", 558, 8));
        D.registrarCoronavirus(new Coronavirus("Dominica", 11, 0));
        D.registrarCoronavirus(new Coronavirus("San Cristobal y Nieves", 2, 0));
        D.registrarCoronavirus(new Coronavirus("San Vicente y Las Granadinas", 1, 0));
        D.registrarCoronavirus(new Coronavirus("Santa Lucia", 3, 0));
        D.registrarCoronavirus(new Coronavirus("Surinam", 8, 0));
        D.registrarCoronavirus(new Coronavirus("Trinidad y Tobago", 65, 1));
        D.registrarCoronavirus(new Coronavirus("Uruguay", 217, 0));

    }

    public void mostrar() {
        D.mostrarCoronavirus();
    }

    public void modificar() {
        if (validar()) {
            D.modificarCoronavirus(new Coronavirus(campo_nombre_pais.getText(), Integer.parseInt(campo_numero_contagios.getText()), Integer.parseInt(campo_numero_muertos.getText())));
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos");
        }

    }

    private void actualizar() {
        D.mostrarCoronavirus();
    }

    private boolean validar() {
        if (campo_nombre_pais.getText().equals("")) {
            return false;
        } else if (campo_numero_contagios.getText().equals("")) {
            return false;
        } else if (campo_numero_muertos.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void eliminar() {
        if (campo_eliminar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor introduzca el nombre del País a eliminar");
        } else {
            D.eliminarCoronavirus(campo_eliminar.getText());
            limpiar();
        }

    }

    private void limpiar() {
        campo_nombre_pais.setText("");
        campo_numero_contagios.setText("");
        campo_numero_muertos.setText("");
        campo_eliminar.setText("");

    }
}
